
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zqfxzllbkgboqdkqokxl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpxZnh6bGxia2dib3Fka3Fva3hsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzMDg4MTAsImV4cCI6MjA1Nzg4NDgxMH0.fxyCDkrMn73nm8aJys0BJpUAgNXKLDY0jsVKoMxertE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
